### PR TITLE
remade force onchange

### PR DESCRIPTION
**Pull request by Pelleson**
remade force onchange since earlier one was broken, added click to auth button and close when popup happens and  added missing colon in css

### CODE REVIEW

**Comment by tam5** [comment]
Hi @Pelleson, thanks for contributing!

Would you mind describing more in detail what problem your PR is solving? I tested it out but could not see any difference in behavior

**Comment by Pelleson** [comment]
When i cloned your project and installed it on chrome the change event didnt fire so you had to manually change and then press auth. When i changed the change event to the code in the PR it works + i added a Quick press and close the popup Window

**Comment by tam5** [comment]
i think i understand, the issue with trying to detect if you have changed your password or not had a bug where it disabled the button the first time. i decided that check is kind of useless so i removed it. Can you see if that fixes your issue? (happy to still merge the typo fix in css)

**Comment by Pelleson** [comment]
I will test it next week

**Comment by Pelleson** [comment]
I tried the updated code and i doesn't work i get an error

image

**Comment by tam5** [comment]
indeed, pushed a fix. does not seem related to this PR. I'm going to close this PR, but feel free to open a new one if issues still arise!

**Pull request closed without merging**
